import type { Metadata } from 'next'
import { Oswald, Archivo } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/header/Navbar'

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ['latin'],
  display: 'swap',
})

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${archivo.variable} antialiased bg-my-bg`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  )
}
