import type { Metadata } from 'next'
import { Oswald, Archivo, Space_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/header/Navbar'
import Footer from '@/sections/Footer'

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ['latin'],
  display: 'swap',
})

const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  display: 'swap',
})

// Utility "logbook" face for v2 notation (week markers, eyebrows, indices)
const spaceMono = Space_Mono({
  variable: '--font-space-mono',
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Toned by Trevor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${oswald.variable} ${archivo.variable} ${spaceMono.variable} antialiased bg-my-bg dark`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
